app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/curtmicro
      username: curtmicro
      password: 'password'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

flyway:
  enabled: true
  locations: classpath:db/migration